
import { useState, useEffect, useRef } from "react";
import Select from 'react-select';
import './Search_recipe.css'
import Navbar from './components/Navbar';
import { useAuth } from './store/auth'
import { useNavigate } from 'react-router-dom';
import Recipe_card from "./Recipe_card";
import Fotter from './components/Footer';

const Search_recipe = () => {
  const [value, setValue] = useState('');
  const [options, setOptions] = useState([]);

  const [dum, setdum] = useState(0)
  const navigateTo = useNavigate();

  // useEffect(() => {
  //   let response = localStorage.getItem('last-search');
  //   if (response) {
  //     // document.getElementById("head").innerHTML = `<h2>Recipes based on selected ingredients<h2>`
  //   }
  // }, [dum])


  const handleChange = selectedOption => {
    setValue(selectedOption);
  };


  const handleInputChange = inputValue => {

    setOptions([
      { value, label: 'spice powder' },
      { value, label: 'acorn squash' },
      { value, label: 'adobo sauce' },
      { value, label: 'agave nectar' },
      { value, label: 'ahi tuna' },
      { value, label: 'alfredo pasta sauce' },
      { value, label: 'almond extract' },
      { value, label: 'almond flour' },
      { value, label: 'almond milk' },
      { value, label: 'almonds' },
      { value, label: 'amaretto' },
      { value, label: 'ancho chiles' },
      { value, label: 'anchovies' },
      { value, label: 'andouille sausage' },
      { value, label: 'angel food cake mix' },
      { value, label: 'angel hair pasta' },
      { value, label: 'angostura bitters' },
      { value, label: 'apple' },
      { value, label: 'apple butter spread' },
      { value, label: 'apple cider' },
      { value, label: 'apple juice' },
      { value, label: 'apple pie spice' },
      { value, label: 'apricot preserves' },
      { value, label: 'apricots' },
      { value, label: 'arborio rice' },
      { value, label: 'arrowroot powder' },
      { value, label: 'artichoke heart quarters' },
      { value, label: 'artichokes' },
      { value, label: 'arugula' },
      { value, label: 'asafoetida' },
      { value, label: 'asafoetida powder' },
      { value, label: 'asiago cheese' },
      { value, label: 'asian pear' },
      { value, label: 'asparagus spears' },
      { value, label: 'avocado' },
      { value, label: 'avocado oil' },
      { value, label: 'baby bell peppers' },
      { value, label: 'baby bok choy' },
      { value, label: 'baby carrots' },
      { value, label: 'baby corn' },
      { value, label: 'baby spinach leaves' },
      { value, label: 'baby-back ribs' },
      { value, label: 'baby-back ribs' },
      { value, label: 'bacon' },
      { value, label: 'bacon fat' },
      { value, label: 'baguette' },
      { value, label: 'baking bar' },
      { value, label: 'baking powder' },
      { value, label: 'baking soda' },
      { value, label: 'balsamic glaze' },
      { value, label: 'balsamic vinegar' },
      { value, label: 'bamboo shoots' },
      { value, label: 'banana' },
      { value, label: 'basmati rice' },
      { value, label: 'bay leaves' },
      { value, label: 'bbq sauce' },
      { value, label: 'beans' },
      { value, label: 'beef' },
      { value, label: 'beef brisket' },
      { value, label: 'beef broth' },
      { value, label: 'beef chuck roast' },
      { value, label: 'beef stock' },
      { value, label: 'beef tenderloin' },
      { value, label: 'beer' },
      { value, label: 'beer' },
      { value, label: 'beets' },
      { value, label: 'bell pepper' },
      { value, label: 'berries' },
      { value, label: 'biscuit mix' },
      { value, label: 'biscuits' },
      { value, label: 'bittersweet chocolate' },
      { value, label: 'black bean sauce' },
      { value, label: 'black beans' },
      { value, label: 'black olives' },
      { value, label: 'black pepper' },
      { value, label: 'black sesame seeds' },
      { value, label: 'blackberries' },
      { value, label: 'blanched almonds' },
      { value, label: 'blood orange' },
      { value, label: 'blue cheese' },
      { value, label: 'blueberries' },
      { value, label: 'bok choy' },
      { value, label: 'boneless skinless chicken breast' },
      { value, label: 'bourbon' },
      { value, label: 'brandy' },
      { value, label: 'bread' },
      { value, label: 'bread flour' },
      { value, label: 'breakfast links' },
      { value, label: 'brie' },
      { value, label: 'broccoli' },
      { value, label: 'broccoli florets' },
      { value, label: 'brown rice' },
      { value, label: 'brown rice flour' },
      { value, label: 'brown sugar' },
      { value, label: 'brownie mix' },
      { value, label: 'brussel sprouts' },
      { value, label: 'bulgur' },
      { value, label: 'butter' },
      { value, label: 'butterhead lettuce' },
      { value, label: 'buttermilk' },
      { value, label: 'butternut squash' },
      { value, label: 'butterscotch chips' },
      { value, label: 'cabbage' },
      { value, label: 'caesar dressing' },
      { value, label: 'cajun seasoning' },
      { value, label: 'cake flour' },
      { value, label: 'candy canes' },
      { value, label: 'candy coating' },
      { value, label: 'candy melts' },
      { value, label: 'canned black beans' },
      { value, label: 'canned diced tomatoes' },
      { value, label: 'canned garbanzo beans' },
      { value, label: 'canned green chiles' },
      { value, label: 'canned kidney beans' },
      { value, label: 'canned mushrooms' },
      { value, label: 'canned pinto beans' },
      { value, label: 'canned red kidney beans' },
      { value, label: 'canned tomatoes' },
      { value, label: 'canned tuna' },
      { value, label: 'canned white beans' },
      { value, label: 'canned white cannellini beans' },
      { value, label: 'cannellini beans' },
      { value, label: 'cantaloupe' },
      { value, label: 'capers' },
      { value, label: 'caramel sauce' },
      { value, label: 'caramels' },
      { value, label: 'caraway seed' },
      { value, label: 'cardamom' },
      { value, label: 'cardamom pods' },
      { value, label: 'carp' },
      { value, label: 'carrots' },
      { value, label: 'cat fish filets' },
      { value, label: 'cauliflower' },
      { value, label: 'cauliflower florets' },
      { value, label: 'cauliflower rice' },
      { value, label: 'celery' },
      { value, label: 'celery ribs' },
      { value, label: 'celery root' },
      { value, label: 'celery salt' },
      { value, label: 'celery seed' },
      { value, label: 'cereal' },
      { value, label: 'champagne' },
      { value, label: 'chana dal' },
      { value, label: 'cheddar' },
      { value, label: 'cheese' },
      { value, label: 'cheese curds' },
      { value, label: 'cheese dip' },
      { value, label: 'cheese soup' },
      { value, label: 'cheese tortellini' },
      { value, label: 'cherry' },
      { value, label: 'cherry pie filling' },
      { value, label: 'cherry tomatoes' },
      { value, label: 'chestnuts' },
      { value, label: 'chia seeds' },
      { value, label: 'chicken base' },
      { value, label: 'chicken bouillon' },
      { value, label: 'chicken bouillon granules' },
      { value, label: 'chicken breasts' },
      { value, label: 'chicken broth' },
      { value, label: 'chicken drumsticks' },
      { value, label: 'chicken legs' },
      { value, label: 'chicken pieces' },
      { value, label: 'chicken sausage' },
      { value, label: 'chicken stock' },
      { value, label: 'chicken tenders' },
      { value, label: 'chicken thighs' },
      { value, label: 'chicken wings' },
      { value, label: 'chickpea' },
      { value, label: 'chile garlic sauce' },
      { value, label: 'chili paste' },
      { value, label: 'chili peppers' },
      { value, label: 'chili powder' },
      { value, label: 'chili sauce' },
      { value, label: 'chipotle chiles in adobo' },
      { value, label: 'chipotle chilies' },
      { value, label: 'chipotle peppers in adobo' },
      { value, label: 'chive & onion cream cheese spread' },
      { value, label: 'chocolate' },
      { value, label: 'chocolate chip cookies' },
      { value, label: 'chocolate chunks' },
      { value, label: 'chocolate ice cream' },
      { value, label: 'chocolate milk' },
      { value, label: 'chocolate sandwich cookies' },
      { value, label: 'chocolate syrup' },
      { value, label: 'chocolate wafer cookies' },
      { value, label: 'chorizo sausage' },
      { value, label: 'cider vinegar' },
      { value, label: 'cilantro' },
      { value, label: 'cinnamon roll' },
      { value, label: 'cinnamon stick' },
      { value, label: 'cinnamon sugar' },
      { value, label: 'cinnamon swirl bread' },
      { value, label: 'clam juice' },
      { value, label: 'clams' },
      { value, label: 'clarified butter' },
      { value, label: 'clove' },
      { value, label: 'coarse salt' },
      { value, label: 'coarsely ground pepper' },
      { value, label: 'cocoa nibs' },
      { value, label: 'cocoa powder' },
      { value, label: 'coconut' },
      { value, label: 'coconut aminos' },
      { value, label: 'coconut butter' },
      { value, label: 'coconut cream' },
      { value, label: 'coconut extract' },
      { value, label: 'coconut flour' },
      { value, label: 'coconut milk' },
      { value, label: 'coconut oil' },
      { value, label: 'coconut water' },
      { value, label: 'cod' },
      { value, label: 'coffee' },
      { value, label: 'cognac' },
      { value, label: 'cola' },
      { value, label: 'colby jack' },
      { value, label: 'collard greens' },
      { value, label: 'condensed cream of celery soup' },
      { value, label: 'condensed cream of mushroom soup' },
      {
        value, label: 'confectioner swerve'
      },
      { value, label: 'cooked bacon' },
      { value, label: 'cooked brown rice' },
      { value, label: 'cooked chicken breast' },
      { value, label: 'cooked ham' },
      { value, label: 'cooked long grain rice' },
      { value, label: 'cooked pasta' },
      { value, label: 'cooked polenta' },
      { value, label: 'cooked quinoa' },
      { value, label: 'cooked wild rice' },
      { value, label: 'cookies' },
      { value, label: 'coriander' },
      { value, label: 'corn' },
      { value, label: 'corn bread mix' },
      { value, label: 'corn chips' },
      { value, label: 'corn flakes cereal' },
      { value, label: 'corn flour' },
      { value, label: 'corn kernels' },
      { value, label: 'corn oil' },
      { value, label: 'corn tortillas' },
      { value, label: 'cornbread' },
      { value, label: 'corned beef' },
      { value, label: 'cornish hens' },
      { value, label: 'cornmeal' },
      { value, label: 'cornstarch' },
      { value, label: 'cotija cheese' },
      { value, label: 'cottage cheese' },
      { value, label: 'country bread' },
      { value, label: 'courgettes' },
      { value, label: 'couscous' },
      { value, label: 'cow pea' },
      { value, label: 'crabmeat' },
      { value, label: 'cracked pepper' },
      { value, label: 'cranberries' },
      { value, label: 'cranberry juice' },
      { value, label: 'cream' },
      { value, label: 'cream cheese' },
      { value, label: 'cream cheese block' },
      { value, label: 'cream of chicken soup' },
      { value, label: 'cream of tartar' },
      { value, label: 'creamed corn' },
      { value, label: 'creamy peanut butter' },
      { value, label: 'creme fraiche' },
      { value, label: 'cremini mushrooms' },
      { value, label: 'creole seasoning' },
      { value, label: 'crisp rice cereal' },
      { value, label: 'croutons' },
      { value, label: 'crystallized ginger' },
      { value, label: 'cucumber' },
      { value, label: 'cumin seeds' },
      { value, label: 'cup cake' },
      { value, label: 'currants' },
      { value, label: 'curry leaves' },
      { value, label: 'dairy free milk' },
      { value, label: 'dark brown sugar' },
      { value, label: 'dark chocolate' },
      { value, label: 'dark chocolate candy bars' },
      { value, label: 'dark chocolate chips' },
      { value, label: 'dark sesame oil' },
      { value, label: 'dates' },
      { value, label: 'deep dish pie crust' },
      { value, label: 'deli ham' },
      { value, label: 'deli turkey' },
      { value, label: 'dessert oats' },
      { value, label: 'dessert wine' },
      { value, label: 'diced ham' },
      { value, label: 'diet pop' },
      { value, label: 'dijon mustard' },
      { value, label: 'dill' },
      { value, label: 'dill pickles' },
      { value, label: 'hot dog' },
      { value, label: 'double cream' },
      { value, label: 'dried apricots' },
      { value, label: 'dried basil' },
      { value, label: 'dried cherries' },
      { value, label: 'dried chorizo' },
      { value, label: 'dried cranberries' },
      { value, label: 'dried dill' },
      { value, label: 'dried onion' },
      { value, label: 'dried porcini mushrooms' },
      { value, label: 'dried rubbed sage' },
      { value, label: 'dried thyme' },
      { value, label: 'dried tomatoes' },
      { value, label: 'dry bread crumbs' },
      { value, label: 'dry milk' },
      { value, label: 'dry mustard' },
      { value, label: 'dry red wine' },
      { value, label: 'dry roasted peanuts' },
      { value, label: 'duck fat' },
      { value, label: 'dutch process cocoa powder' },
      { value, label: 'edamame' },
      { value, label: 'egg substitute' },
      { value, label: 'egg vermicelli' },
      { value, label: 'egg whites' },
      { value, label: 'egg yolk' },
      { value, label: 'eggnog' },
      { value, label: 'eggplant' },
      { value, label: 'elbow macaroni' },
      { value, label: 'enchilada sauce' },
      { value, label: 'english cucumber' },
      { value, label: 'english muffin' },
      { value, label: 'erythritol' },
      { value, label: 'escarole' },
      { value, label: 'espresso' },
      { value, label: 'evaporated milk' },
      { value, label: 'extra firm tofu' },
      { value, label: 'extra virgin olive oil' },
      { value, label: 'farfalle' },
      { value, label: 'farro' },
      { value, label: 'fat free mayo' },
      { value, label: 'fat-free less-sodium chicken broth' },
      { value, label: 'fennel' },
      { value, label: 'fennel seeds' },
      { value, label: 'fenugreek leaf' },
      { value, label: 'fenugreek seeds' },
      { value, label: 'feta cheese' },
      { value, label: 'fettuccine' },
      { value, label: 'fire roasted tomatoes' },
      { value, label: 'fish' },
      { value, label: 'fish sauce' },
      { value, label: 'fish stock' },
      { value, label: 'flank steak' },
      { value, label: 'flax seeds' },
      { value, label: 'fleur de sel' },
      { value, label: 'flour' },
      { value, label: 'flour tortillas' },
      { value, label: 'fontina cheese' },
      { value, label: 'food dye' },
      {
        value, label: 'frank redhot sauce'
      },
      { value, label: 'free range eggs' },
      { value, label: 'french bread' },
      { value, label: 'fresh basil' },
      { value, label: 'fresh bean sprouts' },
      { value, label: 'fresh chives' },
      { value, label: 'fresh corn' },
      { value, label: 'fresh corn kernels' },
      { value, label: 'fresh figs' },
      { value, label: 'fresh fruit' },
      { value, label: 'fresh herbs' },
      { value, label: 'fresh mint' },
      { value, label: 'fresh mozzarella' },
      { value, label: 'fresh rosemary' },
      { value, label: 'fresh thyme leaves' },
      { value, label: 'fried onions' },
      { value, label: 'frosting' },
      { value, label: 'froyo bars' },
      { value, label: 'frozen corn' },
      { value, label: 'frozen spinach' },
      { value, label: 'fudge' },
      { value, label: 'fudge topping' },
      { value, label: 'fun size almond joy bar' },
      { value, label: 'garam masala' },
      { value, label: 'garbanzo bean flour' },
      { value, label: 'garlic' },
      { value, label: 'garlic paste' },
      { value, label: 'garlic powder' },
      { value, label: 'garlic powder' },
      { value, label: 'garlic salt' },
      { value, label: 'gelatin' },
      { value, label: 'gf chocolate cake mix' },
      { value, label: 'gin' },
      { value, label: 'ginger' },
      { value, label: 'ginger ale' },
      { value, label: 'ginger paste' },
      { value, label: 'ginger-garlic paste' },
      { value, label: 'gingersnap cookies' },
      { value, label: 'gnocchi' },
      { value, label: 'goat cheese' },
      { value, label: 'golden raisins' },
      { value, label: 'gorgonzola' },
      { value, label: 'gouda cheese' },
      { value, label: 'graham cracker crumbs' },
      { value, label: 'graham cracker pie crust' },
      { value, label: 'graham crackers' },
      { value, label: 'grain blend' },
      { value, label: 'grand marnier' },
      { value, label: 'granny smith apples' },
      { value, label: 'granola' },
      { value, label: 'granulated garlic' },
      { value, label: 'grape tomatoes' },
      { value, label: 'grapefruit' },
      { value, label: 'grapeseed oil' },
      { value, label: 'gravy' },
      { value, label: 'great northern beans' },
      { value, label: 'greek yogurt' },
      { value, label: 'green beans' },
      { value, label: 'green bell pepper' },
      { value, label: 'green chili pepper' },
      { value, label: 'green food coloring' },
      { value, label: 'green grapes' },
      { value, label: 'green olives' },
      { value, label: 'green onions' },
      { value, label: 'greens' },
      { value, label: 'grill cheese' },
      { value, label: 'grill seasoning' },
      { value, label: 'ground allspice' },
      { value, label: 'ground ancho chili' },
      { value, label: 'ground beef' },
      { value, label: 'ground chicken' },
      { value, label: 'ground chipotle chile pepper' },
      { value, label: 'ground cinnamon' },
      { value, label: 'ground cinnamon' },
      { value, label: 'ground cloves' },
      { value, label: 'ground coriander seeds' },
      { value, label: 'ground cumin' },
      { value, label: 'ground flaxseed' },
      { value, label: 'ground ginger' },
      { value, label: 'ground lamb' },
      { value, label: 'ground mace' },
      { value, label: 'ground nutmeg' },
      { value, label: 'ground pork' },
      { value, label: 'ground pork sausage' },
      { value, label: 'ground veal' },
      { value, label: 'gruyere' },
      { value, label: 'guacamole' },
      { value, label: 'half n half' },
      { value, label: 'halibut fillet' },
      { value, label: 'ham' },
      { value, label: 'hamburger buns' },
      { value, label: 'hard cooked eggs' },
      { value, label: 'harissa' },
      { value, label: 'hash brown potatoes' },
      { value, label: 'hazelnuts' },
      { value, label: 'healthy request cream of celery soup' },
      { value, label: 'hemp seeds' },
      { value, label: 'herbes de provence' },
      { value, label: 'herbs' },
      {
        value, label: 'hershey kisses brand milk chocolates'
      },
      { value, label: 'hoisin sauce' },
      { value, label: 'honey mustard' },
      { value, label: 'horseradish' },
      { value, label: 'hot sauce' },
      { value, label: 'hummus' },
      { value, label: 'ice' },
      { value, label: 'ice cream' },
      { value, label: 'instant chocolate pudding mix' },
      { value, label: 'instant coffee powder' },
      { value, label: 'instant espresso powder' },
      { value, label: 'instant lemon pudding mix' },
      { value, label: 'instant yeast' },
      { value, label: 'irish cream' },
      { value, label: 'italian bread' },
      { value, label: 'italian cheese blend' },
      { value, label: 'italian sausages' },
      { value, label: 'italian seasoning' },
      { value, label: 'jaggery' },
      { value, label: 'jalapeno' },
      { value, label: 'jasmine rice' },
      { value, label: 'jelly' },
      { value, label: 'jicama' },
      { value, label: 'jimmies' },
      { value, label: 'juice' },
      { value, label: 'jumbo shell pasta' },
      { value, label: 'kaffir lime leaves' },
      { value, label: 'kahlua' },
      { value, label: 'kalamata olives' },
      { value, label: 'kale' },
      { value, label: 'ketchup' },
      { value, label: 'kitchen bouquet' },
      { value, label: 'kiwis' },
      { value, label: 'kosher salt' },
      { value, label: 'ladyfingers' },
      { value, label: 'lamb' },
      { value, label: 'lasagna noodles' },
      { value, label: 'lb cake' },
      { value, label: 'lean ground beef' },
      { value, label: 'lean ground turkey' },
      { value, label: 'lean pork tenderloin' },
      { value, label: 'leeks' },
      { value, label: 'leg of lamb' },
      { value, label: 'lemon' },
      { value, label: 'lemon curd' },
      { value, label: 'lemon extract' },
      { value, label: 'lemon juice' },
      { value, label: 'lemon peel' },
      { value, label: 'lemon pepper' },
      { value, label: 'lemon wedges' },
      { value, label: 'lemongrass' },
      { value, label: 'lettuce' },
      { value, label: 'lettuce leaves' },
      { value, label: 'light butter' },
      { value, label: 'light coconut milk' },
      { value, label: 'light corn syrup' },
      { value, label: 'light cream cheese' },
      { value, label: 'light mayonnaise' },
      { value, label: 'light olive oil' },
      { value, label: 'light soy sauce' },
      { value, label: 'lime' },
      { value, label: 'lime juice' },
      { value, label: 'lime wedges' },
      { value, label: 'lime zest' },
      { value, label: 'linguine' },
      { value, label: 'liquid smoke' },
      { value, label: 'liquid stevia' },
      { value, label: 'liquor' },
      { value, label: 'live lobster' },
      { value, label: 'long-grain rice' },
      { value, label: 'low fat buttermilk' },
      { value, label: 'low fat milk' },
      { value, label: 'low fat milk' },
      { value, label: 'low fat plain yogurt' },
      { value, label: 'low fat ricotta cheese' },
      { value, label: 'low fat sour cream' },
      { value, label: 'low sodium chicken broth' },
      { value, label: 'low sodium soy sauce' },
      { value, label: 'low-sodium chicken stock' },
      { value, label: 'lower sodium beef broth' },
      { value, label: 'lump crab' },
      { value, label: 'm&m candies' },
      { value, label: 'macadamia nuts' },
      { value, label: 'macaroni and cheese mix' },
      { value, label: 'madras curry powder' },
      { value, label: 'malt drink mix' },
      { value, label: 'mandarin orange sections' },
      { value, label: 'mandarin oranges' },
      { value, label: 'mango' },
      { value, label: 'maple syrup' },
      { value, label: 'maraschino cherries' },
      { value, label: 'margarine' },
      { value, label: 'marinara sauce' },
      { value, label: 'marjoram' },
      { value, label: 'marsala wine' },
      { value, label: 'marshmallow fluff' },
      { value, label: 'marshmallows' },
      { value, label: 'masa harina' },
      { value, label: 'mascarpone' },
      { value, label: 'mat beans' },
      { value, label: 'matcha tea' },
      { value, label: 'mayonnaise' },
      { value, label: 'meat' },
      { value, label: 'meat' },
      { value, label: 'meatballs' },
      { value, label: 'medjool dates' },
      { value, label: 'mexican cream' },
      { value, label: 'meyer lemon juice' },
      { value, label: 'milk' },
      { value, label: 'milk chocolate chips' },
      { value, label: 'mint chutney' },
      { value, label: 'minute rice' },
      { value, label: 'miracle whip' },
      { value, label: 'mirin' },
      { value, label: 'miso' },
      { value, label: 'molasses' },
      { value, label: 'monterey jack cheese' },
      { value, label: 'mushroom' },
      { value, label: 'mussels' },
      { value, label: 'mustard' },
      { value, label: 'mustard seeds' },
      { value, label: 'napa cabbage' },
      { value, label: 'navel oranges' },
      { value, label: 'nectarine' },
      { value, label: 'new potatoes' },
      { value, label: 'non-fat greek yogurt' },
      { value, label: 'nonfat cool whip' },
      { value, label: 'nonfat milk' },
      { value, label: 'nori' },
      { value, label: 'nut butter' },
      { value, label: 'nut meal' },
      { value, label: 'nutella' },
      { value, label: 'nutritional yeast' },
      { value, label: 'oat flour' },
      { value, label: 'oats' },
      { value, label: 'oil' },
      { value, label: 'oil packed sun dried tomatoes' },
      { value, label: 'okra' },
      { value, label: 'old bay seasoning' },
      { value, label: 'olive oil' },
      { value, label: 'olives' },
      { value, label: 'onion' },
      { value, label: 'onion powder' },
      { value, label: 'onion soup mix' },
      { value, label: 'orange' },
      { value, label: 'orange bell pepper' },
      { value, label: 'orange juice' },
      { value, label: 'orange juice concentrate' },
      { value, label: 'orange liqueur' },
      { value, label: 'orange marmalade' },
      { value, label: 'orange oil' },
      { value, label: 'orange zest' },
      { value, label: 'oregano' },
      { value, label: 'oreo cookies' },
      { value, label: 'orzo' },
      { value, label: 'oyster sauce' },
      { value, label: 'oysters' },
      { value, label: 'palm sugar' },
      { value, label: 'pancetta' },
      { value, label: 'paneer' },
      { value, label: 'panko' },
      { value, label: 'papaya' },
      { value, label: 'paprika' },
      { value, label: 'parmigiano reggiano' },
      { value, label: 'parsley' },
      { value, label: 'parsley flakes' },
      { value, label: 'parsnip' },
      { value, label: 'part-skim mozzarella cheese' },
      { value, label: 'pasta' },
      { value, label: 'pasta salad mix' },
      { value, label: 'pasta sauce' },
      { value, label: 'pastry flour' },
      { value, label: 'peach' },
      { value, label: 'peanut butter' },
      { value, label: 'peanut butter chips' },
      { value, label: 'peanut butter cups' },
      { value, label: 'peanut oil' },
      { value, label: 'peanuts' },
      { value, label: 'pear liqueur' },
      { value, label: 'pearl barley' },
      { value, label: 'pearl onions' },
      { value, label: 'peas' },
      { value, label: 'pecan' },
      { value, label: 'pecan pieces' },
      { value, label: 'pecorino' },
      { value, label: 'penne' },
      { value, label: 'peperoncino' },
      { value, label: 'pepper jack cheese' },
      { value, label: 'peppercorns' },
      { value, label: 'peppermint baking chips' },
      { value, label: 'peppermint extract' },
      { value, label: 'pepperoni' },
      { value, label: 'peppers' },
      { value, label: 'pesto' },
      { value, label: 'pickle relish' },
      { value, label: 'pickles' },
      { value, label: 'pico de gallo' },
      { value, label: 'pie crust' },
      { value, label: 'pimento stuffed olives' },
      { value, label: 'pimientos' },
      { value, label: 'pine nuts' },
      { value, label: 'pineapple' },
      { value, label: 'pineapple chunks' },
      { value, label: 'pineapple in juice' },
      { value, label: 'pineapple juice' },
      { value, label: 'pink himalayan salt' },
      { value, label: 'pinto beans' },
      { value, label: 'pistachios' },
      { value, label: 'pita' },
      { value, label: 'pizza crust' },
      { value, label: 'pizza mix' },
      { value, label: 'plain greek yogurt' },
      { value, label: 'plain nonfat yogurt' },
      { value, label: 'plain yogurt' },
      { value, label: 'plantain' },
      { value, label: 'plum' },
      { value, label: 'plum tomatoes' },
      { value, label: 'poblano peppers' },
      { value, label: 'polenta' },
      { value, label: 'polish sausage' },
      { value, label: 'pomegranate juice' },
      { value, label: 'pomegranate molasses' },
      { value, label: 'pomegranate seeds' },
      { value, label: 'popcorn' },
      { value, label: 'poppy seeds' },
      { value, label: 'pork' },
      { value, label: 'Pork & Beans' },
      { value, label: 'pork belly' },
      { value, label: 'pork butt' },
      { value, label: 'pork chops' },
      { value, label: 'pork links' },
      { value, label: 'pork loin chops' },
      { value, label: 'pork loin roast' },
      { value, label: 'pork roast' },
      { value, label: 'pork shoulder' },
      { value, label: 'pork tenderloin' },
      { value, label: 'port' },
      { value, label: 'portabella mushrooms' },
      { value, label: 'pot roast' },
      { value, label: 'potato chips' },
      { value, label: 'potato starch' },
      { value, label: 'potatoes' },
      { value, label: 'poultry seasoning' },
      { value, label: 'powdered sugar' },
      { value, label: 'pretzel sandwiches' },
      { value, label: 'processed american cheese' },
      { value, label: 'prosciutto' },
      { value, label: 'provolone cheese' },
      { value, label: 'prunes' },
      { value, label: 'puff pastry' },
      { value, label: 'pumpkin' },
      { value, label: 'pumpkin pie filling' },
      { value, label: 'pumpkin pie spice' },
      { value, label: 'pumpkin puree' },
      { value, label: 'pumpkin seeds' },
      { value, label: 'queso fresco' },
      { value, label: 'quick cooking oats' },
      { value, label: 'quinoa' },
      { value, label: 'quinoa flour' },
      { value, label: 'radicchio' },
      { value, label: 'radishes' },
      { value, label: 'raisins' },
      { value, label: 'rajma masala' },
      { value, label: 'ramen noodles' },
      { value, label: 'ranch dressing' },
      { value, label: 'ranch dressing mix' },
      { value, label: 'raspberries' },
      { value, label: 'raspberry jam' },
      { value, label: 'raw cashews' },
      { value, label: 'raw shrimp' },
      { value, label: 'ready-to-serve Asian fried rice' },
      { value, label: 'real bacon recipe pieces' },
      { value, label: 'red apples' },
      { value, label: 'red bell peppers' },
      { value, label: 'red cabbage' },
      { value, label: 'red chilli' },
      { value, label: 'red delicious apples' },
      { value, label: 'red food coloring' },
      { value, label: 'red grapefruit juice' },
      { value, label: 'red grapes' },
      { value, label: 'red kidney beans' },
      { value, label: 'red lentils' },
      { value, label: 'red onion' },
      { value, label: 'red pepper flakes' },
      { value, label: 'red pepper powder' },
      { value, label: 'red potatoes' },
      { value, label: 'red velvet cookie' },
      { value, label: 'red wine' },
      { value, label: 'red wine vinegar' },
      { value, label: 'reduced fat shredded cheddar cheese' },
      { value, label: 'refried beans' },
      { value, label: 'refrigerated crescent rolls' },
      { value, label: 'refrigerated pizza dough' },
      { value, label: 'refrigerated sugar cookie dough' },
      { value, label: 'rhubarb' },
      { value, label: 'rib tips' },
      { value, label: 'rice' },
      { value, label: 'rice flour' },
      { value, label: 'rice krispies cereal' },
      { value, label: 'rice milk' },
      { value, label: 'rice noodles' },
      { value, label: 'rice paper' },
      { value, label: 'rice syrup' },
      { value, label: 'rice vinegar' },
      { value, label: 'rice wine' },
      { value, label: 'ricotta salata' },
      { value, label: 'ritz crackers' },
      { value, label: 'roast beef' },
      { value, label: 'roasted chicken' },
      { value, label: 'roasted nuts' },
      { value, label: 'roasted peanuts' },
      { value, label: 'roasted red peppers' },
      { value, label: 'roma tomatoes' },
      { value, label: 'romaine lettuce' },
      { value, label: 'root vegetables' },
      { value, label: 'rosemary' },
      { value, label: 'rotini pasta' },
      { value, label: 'rotisserie chicken' },
      { value, label: 'round steak' },
      { value, label: 'rub' },
      { value, label: 'rum extract' },
      { value, label: 'runny honey' },
      { value, label: 'russet potatoes' },
      { value, label: 'rutabaga' },
      { value, label: 'rye bread' },
      { value, label: 'rye meal' },
      { value, label: 'saffron threads' },
      { value, label: 'sage' },
      { value, label: 'sage leaves' },
      { value, label: 'salad dressing' },
      { value, label: 'salami' },
      { value, label: 'salmon fillet' },
      { value, label: 'salsa' },
      { value, label: 'salsa verde' },
      { value, label: 'salt' },
      { value, label: 'salt and pepper' },
      { value, label: 'salted butter' },
      { value, label: 'saltine crackers' },
      { value, label: 'sandwich bun' },
      { value, label: 'sauerkraut' },
      { value, label: 'sausage' },
      { value, label: 'sausage links' },
      { value, label: 'scotch bonnet chili' },
      { value, label: 'sea salt' },
      { value, label: 'sea scallops' },
      { value, label: 'seasoned bread crumbs' },
      { value, label: 'seasoned rice vinegar' },
      { value, label: 'seasoned salt' },
      { value, label: 'seasoning' },
      { value, label: 'seasoning blend' },
      { value, label: 'seeds' },
      { value, label: 'self-rising flour' },
      { value, label: 'semi sweet chocolate chips' },
      { value, label: 'serrano chile' },
      { value, label: 'sesame oil' },
      { value, label: 'sesame seed hamburger buns' },
      { value, label: 'sesame seeds' },
      { value, label: 'shallot' },
      { value, label: 'sharp cheddar cheese' },
      { value, label: 'sheeps milk cheese' },
      { value, label: 'shells' },
      { value, label: 'sherry' },
      { value, label: 'sherry' },
      { value, label: 'sherry vinegar' },
      { value, label: 'shiitake mushroom caps' },
      { value, label: 'short grain rice' },
      { value, label: 'short pasta' },
      { value, label: 'short ribs' },
      { value, label: 'shortbread cookies' },
      { value, label: 'shortcrust pastry' },
      { value, label: 'shortening' },
      { value, label: 'shredded cheddar cheese' },
      { value, label: 'shredded cheese' },
      { value, label: 'shredded chicken' },
      { value, label: 'shredded coconut' },
      { value, label: 'shredded mexican cheese blend' },
      { value, label: 'shredded mexican cheese blend' },
      { value, label: 'shredded mozzarella' },
      { value, label: 'silken tofu' },
      { value, label: 'sirloin steak' },
      { value, label: 'skim milk ricotta' },
      { value, label: 'skim vanilla greek yogurt' },
      { value, label: 'skin-on bone-in chicken leg quarters' },
      { value, label: 'skinless boneless chicken breast halves' },
      { value, label: 'skinless boneless chicken thighs' },
      { value, label: 'skinned black gram' },
      { value, label: 'slaw dressing' },
      { value, label: 'slaw mix' },
      { value, label: 'slivered almonds' },
      { value, label: 'smoked paprika' },
      { value, label: 'smoked salmon' },
      { value, label: 'smoked sausage' },
      { value, label: 'smooth peanut butter' },
      { value, label: 'snapper fillets' },
      { value, label: 'snow peas' },
      { value, label: 'soda water' },
      { value, label: 'sour cream' },
      { value, label: 'sourdough bowl' },
      { value, label: 'sourdough bread' },
      { value, label: 'soy milk' },
      { value, label: 'soy protein powder' },
      { value, label: 'soy sauce' },
      { value, label: 'spaghetti' },
      { value, label: 'spaghetti squash' },
      { value, label: 'sparkling wine' },
      { value, label: 'spelt flour' },
      { value, label: 'spicy brown mustard' },
      { value, label: 'spinach' },
      { value, label: 'sprite' },
      { value, label: 'sprouts' },
      { value, label: 'squash' },
      { value, label: 'sriracha sauce' },
      { value, label: 'steaks' },
      { value, label: 'steel cut oats' },
      { value, label: 'stevia' },
      { value, label: 'stew meat' },
      { value, label: 'stew vegetables' },
      { value, label: 'stock' },
      { value, label: 'store-bought phyllo' },
      { value, label: 'stout' },
      { value, label: 'strawberries' },
      { value, label: 'strawberry jam' },
      { value, label: 'strawberry jello' },
      { value, label: 'stuffing' },
      { value, label: 'stuffing mix' },
      { value, label: 'sub rolls' },
      { value, label: 'sugar' },
      { value, label: 'sugar snap peas' },
      { value, label: 'sugar syrup' },
      { value, label: 'sukrin sweetener' },
      { value, label: 'summer savory' },
      { value, label: 'summer squash' },
      { value, label: 'sunflower oil' },
      { value, label: 'sunflower seeds' },
      { value, label: 'sweet chilli sauce' },
      { value, label: 'sweet onion' },
      { value, label: 'sweet paprika' },
      { value, label: 'sweet pickle juice' },
      { value, label: 'sweet pickle relish' },
      { value, label: 'sweet potato' },
      { value, label: 'sweet tea' },
      { value, label: 'sweetened coconut' },
      { value, label: 'sweetened condensed milk' },
      { value, label: 'sweetened shredded coconut' },
      { value, label: 'swiss chard' },
      { value, label: 'swiss cheese' },
      { value, label: 'taco seasoning mix' },
      { value, label: 'taco shells' },
      { value, label: 'tahini' },
      { value, label: 'tamari' },
      { value, label: 'tapioca flour' },
      { value, label: 'tarragon' },
      { value, label: 'tart apple' },
      { value, label: 'tea bags' },
      { value, label: 'tequila' },
      { value, label: 'teriyaki sauce' },
      { value, label: 'thai basil' },
      { value, label: 'thai chiles' },
      { value, label: 'thai red curry paste' },
      { value, label: 'thick-cut bacon' },
      { value, label: 'tilapia fillets' },
      { value, label: 'toast' },
      { value, label: 'toffee bits' },
      { value, label: 'tofu' },
      { value, label: 'tomatillos' },
      { value, label: 'tomato juice' },
      { value, label: 'tomato paste' },
      { value, label: 'tomato puree' },
      { value, label: 'tomato sauce' },
      { value, label: 'tomato soup' },
      { value, label: 'tomatoes' },
      { value, label: 'top blade steak' },
      { value, label: 'top round steak' },
      { value, label: 'Top Sirloin' },
      { value, label: 'tortilla' },
      { value, label: 'tortilla chips' },
      { value, label: 'triple sec' },
      { value, label: 'truffle oil' },
      { value, label: 'tuna' },
      { value, label: 'turbinado sugar' },
      { value, label: 'turkey' },
      { value, label: 'turkey breast' },
      { value, label: 'turkey kielbasa' },
      { value, label: 'turmeric' },
      { value, label: 'turnips' },
      { value, label: 'unbleached flour' },
      { value, label: 'unsalted butter' },
      { value, label: 'unsmoked back bacon' },
      { value, label: 'unsweetened applesauce' },
      { value, label: 'unsweetened coconut milk' },
      { value, label: 'unsweetened shredded coconut' },
      { value, label: 'vanilla bean' },
      { value, label: 'vanilla bean paste' },
      { value, label: 'vanilla essence' },
      { value, label: 'vanilla extract' },
      { value, label: 'vanilla frosting' },
      { value, label: 'vanilla instant pudding mix' },
      { value, label: 'vanilla protein powder' },
      { value, label: 'vanilla wafers' },
      { value, label: 'vanilla yogurt' },
      { value, label: 'vegan cheese' },
      { value, label: 'vegan chocolate chips' },
      { value, label: 'vegan margarine' },
      { value, label: 'vegetable broth' },
      { value, label: 'vegetable oil' },
      { value, label: 'vegetarian bacon' },
      { value, label: 'vermouth' },
      { value, label: 'vinaigrette' },
      { value, label: 'vinegar' },
      { value, label: 'vodka' },
      { value, label: 'walnuts' },
      { value, label: 'water' },
      { value, label: 'water chestnuts' },
      { value, label: 'water-packed tuna' },
      { value, label: 'watercress' },
      { value, label: 'watermelon chunks' },
      { value, label: 'wheat bran' },
      { value, label: 'wheat germ' },
      { value, label: 'whipped cream' },
      { value, label: 'whipped topping' },
      { value, label: 'whipping cream' },
      { value, label: 'whiskey' },
      { value, label: 'white balsamic vinegar' },
      { value, label: 'white bread' },
      { value, label: 'white cake mix' },
      { value, label: 'white cheddar' },
      { value, label: 'white chocolate' },
      { value, label: 'white chocolate chips' },
      { value, label: 'white onion' },
      { value, label: 'white pepper' },
      { value, label: 'white whole wheat flour' },
      { value, label: 'white wine' },
      { value, label: 'white wine vinegar' },
      { value, label: 'whole allspice berries' },
      { value, label: 'whole chicken' },
      { value, label: 'whole coriander seeds' },
      { value, label: 'whole cranberry sauce' },
      { value, label: 'whole kernel corn' },
      { value, label: 'whole star anise' },
      { value, label: 'whole wheat bread' },
      { value, label: 'whole wheat flour' },
      { value, label: 'whole wheat tortillas' },
      { value, label: 'whole-grain mustard' },
      { value, label: 'wine' },
      { value, label: 'wine vinegar' },
      { value, label: 'winter squash' },
      { value, label: 'won ton wraps' },
      { value, label: 'worcestershire sauce' },
      { value, label: 'wraps' },
      { value, label: 'xanthan gum' },
      { value, label: 'yeast' },
      { value, label: 'yellow bell pepper' },
      { value, label: 'yellow cake mix' },
      { value, label: 'yellow onion' },
      { value, label: 'yogurt' },
      { value, label: 'yukon gold potato' }

    ]);
  };

  const add_ingredient_to_lst = () => {
    let lst = document.getElementById("list");
    // let selected_set = lst.innerHTML.split('<br>');

    let flag = 1;
    if (value.label == undefined) flag = 0;

    if (flag) {
      let li = document.createElement('li');
      li.innerHTML = value.label;
      li.classList.add("item");
      lst.appendChild(li);

      let span = document.createElement("span");
      span.innerHTML = "\u00d7";
      span.classList.add("span");
      span.addEventListener("click", function (e) {
        if (e.target.tagName === "SPAN") {
          e.target.parentElement.remove();
        }
      }, false);
      li.appendChild(span);
    }
  }

  // document.getElementById("list").addEventListener("click", function(e){
  //   if(e.target.tagName === "SPAN"){
  //     e.tagName.parentElement.remove();
  //   }
  // },false);  

  const get_recipe_from_api = async () => {
    let queryy = "";
    let lst = document.getElementById("list");
    let selected_set = lst.innerHTML.split('<br>');

    let flag = 1;
    if (selected_set.length == 1 && selected_set[0] == '') flag = 0;


    selected_set.forEach(ingredient => {
      if (ingredient != '')
        queryy += ingredient + ",+";
    })

    queryy = queryy.slice(0, -2);


    if (flag) {
      let recipies = document.getElementById("recipes")

      const options = { method: 'GET' };

      const raw_response = await fetch(`https://api.spoonacular.com/recipes/findByIngredients?apiKey=7f7543ed5a09491c8d1e89145f5caf81&ingredients=${queryy}&number=10&ranking=1&ignorePantry=true`, options)

      console.log(queryy);

      // const raw_response = await fetch(`https://api.spoonacular.com/recipes/search?apiKey=7f7543ed5a09491c8d1e89145f5caf81&includeIngredients=${queryy}&instructionsRequired=true&addRecipeInstructions=true`,options)

      const response = await raw_response.json();

      localStorage.setItem('last-search', JSON.stringify(response))
      setdum(dum + 1)

    }

    else alert(`Please select at least one ingredient`);
  }


  const clear = () => {
    // localStorage.setItem('last-search', JSON.stringify([]));
    localStorage.removeItem('last-search');
    window.location.reload();
  }

  const customStyles = {
    option: (provided, state) => ({
      ...provided,
      backgroundColor: 'rgb(94, 92, 92)',
      color: '#fff',
    }),
  };

  return (
    <>
      <Navbar />
      <div className="mg">
        <Select id="ing" className="searchBar"
          value={value}
          onChange={handleChange}
          onInputChange={handleInputChange}
          options={options}
          styles={customStyles}
          isClearable
          placeholder="Type ingredients..."
        />
        
        <div className='button-container'>
          <button id="add_ingredient" className='search-component-button' onClick={add_ingredient_to_lst}>Add</button>
          <button id="get_recipe" className='search-component-button' onClick={get_recipe_from_api}>Get Yummy Recipes !!</button>
          <button id="clear" className='search-component-button' onClick={clear}>Clear</button>
        </div>
        <ul id="list" className="lst_container"></ul>
        {/* <h2>selected ingredients</h2> */}
        {/* <h2 id="head"></h2> */}
        <div className="recipes-container">

          {[...Array(10)].map((_, index) => (
            <Recipe_card key={index} ind={index} />  
          ))}

        </div>
      </div>

      <Fotter />
    </>
  );

};


export default Search_recipe;

