import { useState, useEffect, useRef } from "react";
import Select from 'react-select';
import './Search_recipe.css'
import Navbar from './components/Navbar';
// import { useAuth } from './store/auth';
import { useNavigate } from 'react-router-dom';
import Video_card from "./Video_card";
import Fotter from './components/Footer';

const Search_video = () => {
    const [Value2, setValue2] = useState('');
    const [options2, setoptions2] = useState([]);

    const [dum2, setdum2] = useState(0)
    const navigateTo = useNavigate();

    const handleChange = selectedOption => {
        setValue2(selectedOption);
    };

    const handleInputChange = inputValue2 => {

        setoptions2([
            { Value2, label: 'spice powder' },
            { Value2, label: 'acorn squash' },
            { Value2, label: 'adobo sauce' },
            { Value2, label: 'agave nectar' },
            { Value2, label: 'ahi tuna' },
            { Value2, label: 'alfredo pasta sauce' },
            { Value2, label: 'almond extract' },
            { Value2, label: 'almond flour' },
            { Value2, label: 'almond milk' },
            { Value2, label: 'almonds' },
            { Value2, label: 'amaretto' },
            { Value2, label: 'ancho chiles' },
            { Value2, label: 'anchovies' },
            { Value2, label: 'andouille sausage' },
            { Value2, label: 'angel food cake mix' },
            { Value2, label: 'angel hair pasta' },
            { Value2, label: 'angostura bitters' },
            { Value2, label: 'apple' },
            { Value2, label: 'apple butter spread' },
            { Value2, label: 'apple cider' },
            { Value2, label: 'apple juice' },
            { Value2, label: 'apple pie spice' },
            { Value2, label: 'apricot preserves' },
            { Value2, label: 'apricots' },
            { Value2, label: 'arborio rice' },
            { Value2, label: 'arrowroot powder' },
            { Value2, label: 'artichoke heart quarters' },
            { Value2, label: 'artichokes' },
            { Value2, label: 'arugula' },
            { Value2, label: 'asafoetida' },
            { Value2, label: 'asafoetida powder' },
            { Value2, label: 'asiago cheese' },
            { Value2, label: 'asian pear' },
            { Value2, label: 'asparagus spears' },
            { Value2, label: 'avocado' },
            { Value2, label: 'avocado oil' },
            { Value2, label: 'baby bell peppers' },
            { Value2, label: 'baby bok choy' },
            { Value2, label: 'baby carrots' },
            { Value2, label: 'baby corn' },
            { Value2, label: 'baby spinach leaves' },
            { Value2, label: 'baby-back ribs' },
            { Value2, label: 'baby-back ribs' },
            { Value2, label: 'bacon' },
            { Value2, label: 'bacon fat' },
            { Value2, label: 'baguette' },
            { Value2, label: 'baking bar' },
            { Value2, label: 'baking powder' },
            { Value2, label: 'baking soda' },
            { Value2, label: 'balsamic glaze' },
            { Value2, label: 'balsamic vinegar' },
            { Value2, label: 'bamboo shoots' },
            { Value2, label: 'banana' },
            { Value2, label: 'basmati rice' },
            { Value2, label: 'bay leaves' },
            { Value2, label: 'bbq sauce' },
            { Value2, label: 'beans' },
            { Value2, label: 'beef' },
            { Value2, label: 'beef brisket' },
            { Value2, label: 'beef broth' },
            { Value2, label: 'beef chuck roast' },
            { Value2, label: 'beef stock' },
            { Value2, label: 'beef tenderloin' },
            { Value2, label: 'beer' },
            { Value2, label: 'beer' },
            { Value2, label: 'beets' },
            { Value2, label: 'bell pepper' },
            { Value2, label: 'berries' },
            { Value2, label: 'biscuit mix' },
            { Value2, label: 'biscuits' },
            { Value2, label: 'bittersweet chocolate' },
            { Value2, label: 'black bean sauce' },
            { Value2, label: 'black beans' },
            { Value2, label: 'black olives' },
            { Value2, label: 'black pepper' },
            { Value2, label: 'black sesame seeds' },
            { Value2, label: 'blackberries' },
            { Value2, label: 'blanched almonds' },
            { Value2, label: 'blood orange' },
            { Value2, label: 'blue cheese' },
            { Value2, label: 'blueberries' },
            { Value2, label: 'bok choy' },
            { Value2, label: 'boneless skinless chicken breast' },
            { Value2, label: 'bourbon' },
            { Value2, label: 'brandy' },
            { Value2, label: 'bread' },
            { Value2, label: 'bread flour' },
            { Value2, label: 'breakfast links' },
            { Value2, label: 'brie' },
            { Value2, label: 'broccoli' },
            { Value2, label: 'broccoli florets' },
            { Value2, label: 'brown rice' },
            { Value2, label: 'brown rice flour' },
            { Value2, label: 'brown sugar' },
            { Value2, label: 'brownie mix' },
            { Value2, label: 'brussel sprouts' },
            { Value2, label: 'bulgur' },
            { Value2, label: 'butter' },
            { Value2, label: 'butterhead lettuce' },
            { Value2, label: 'buttermilk' },
            { Value2, label: 'butternut squash' },
            { Value2, label: 'butterscotch chips' },
            { Value2, label: 'cabbage' },
            { Value2, label: 'caesar dressing' },
            { Value2, label: 'cajun seasoning' },
            { Value2, label: 'cake flour' },
            { Value2, label: 'candy canes' },
            { Value2, label: 'candy coating' },
            { Value2, label: 'candy melts' },
            { Value2, label: 'canned black beans' },
            { Value2, label: 'canned diced tomatoes' },
            { Value2, label: 'canned garbanzo beans' },
            { Value2, label: 'canned green chiles' },
            { Value2, label: 'canned kidney beans' },
            { Value2, label: 'canned mushrooms' },
            { Value2, label: 'canned pinto beans' },
            { Value2, label: 'canned red kidney beans' },
            { Value2, label: 'canned tomatoes' },
            { Value2, label: 'canned tuna' },
            { Value2, label: 'canned white beans' },
            { Value2, label: 'canned white cannellini beans' },
            { Value2, label: 'cannellini beans' },
            { Value2, label: 'cantaloupe' },
            { Value2, label: 'capers' },
            { Value2, label: 'caramel sauce' },
            { Value2, label: 'caramels' },
            { Value2, label: 'caraway seed' },
            { Value2, label: 'cardamom' },
            { Value2, label: 'cardamom pods' },
            { Value2, label: 'carp' },
            { Value2, label: 'carrots' },
            { Value2, label: 'cat fish filets' },
            { Value2, label: 'cauliflower' },
            { Value2, label: 'cauliflower florets' },
            { Value2, label: 'cauliflower rice' },
            { Value2, label: 'celery' },
            { Value2, label: 'celery ribs' },
            { Value2, label: 'celery root' },
            { Value2, label: 'celery salt' },
            { Value2, label: 'celery seed' },
            { Value2, label: 'cereal' },
            { Value2, label: 'champagne' },
            { Value2, label: 'chana dal' },
            { Value2, label: 'cheddar' },
            { Value2, label: 'cheese' },
            { Value2, label: 'cheese curds' },
            { Value2, label: 'cheese dip' },
            { Value2, label: 'cheese soup' },
            { Value2, label: 'cheese tortellini' },
            { Value2, label: 'cherry' },
            { Value2, label: 'cherry pie filling' },
            { Value2, label: 'cherry tomatoes' },
            { Value2, label: 'chestnuts' },
            { Value2, label: 'chia seeds' },
            { Value2, label: 'chicken base' },
            { Value2, label: 'chicken bouillon' },
            { Value2, label: 'chicken bouillon granules' },
            { Value2, label: 'chicken breasts' },
            { Value2, label: 'chicken broth' },
            { Value2, label: 'chicken drumsticks' },
            { Value2, label: 'chicken legs' },
            { Value2, label: 'chicken pieces' },
            { Value2, label: 'chicken sausage' },
            { Value2, label: 'chicken stock' },
            { Value2, label: 'chicken tenders' },
            { Value2, label: 'chicken thighs' },
            { Value2, label: 'chicken wings' },
            { Value2, label: 'chickpea' },
            { Value2, label: 'chile garlic sauce' },
            { Value2, label: 'chili paste' },
            { Value2, label: 'chili peppers' },
            { Value2, label: 'chili powder' },
            { Value2, label: 'chili sauce' },
            { Value2, label: 'chipotle chiles in adobo' },
            { Value2, label: 'chipotle chilies' },
            { Value2, label: 'chipotle peppers in adobo' },
            { Value2, label: 'chive & onion cream cheese spread' },
            { Value2, label: 'chocolate' },
            { Value2, label: 'chocolate chip cookies' },
            { Value2, label: 'chocolate chunks' },
            { Value2, label: 'chocolate ice cream' },
            { Value2, label: 'chocolate milk' },
            { Value2, label: 'chocolate sandwich cookies' },
            { Value2, label: 'chocolate syrup' },
            { Value2, label: 'chocolate wafer cookies' },
            { Value2, label: 'chorizo sausage' },
            { Value2, label: 'cider vinegar' },
            { Value2, label: 'cilantro' },
            { Value2, label: 'cinnamon roll' },
            { Value2, label: 'cinnamon stick' },
            { Value2, label: 'cinnamon sugar' },
            { Value2, label: 'cinnamon swirl bread' },
            { Value2, label: 'clam juice' },
            { Value2, label: 'clams' },
            { Value2, label: 'clarified butter' },
            { Value2, label: 'clove' },
            { Value2, label: 'coarse salt' },
            { Value2, label: 'coarsely ground pepper' },
            { Value2, label: 'cocoa nibs' },
            { Value2, label: 'cocoa powder' },
            { Value2, label: 'coconut' },
            { Value2, label: 'coconut aminos' },
            { Value2, label: 'coconut butter' },
            { Value2, label: 'coconut cream' },
            { Value2, label: 'coconut extract' },
            { Value2, label: 'coconut flour' },
            { Value2, label: 'coconut milk' },
            { Value2, label: 'coconut oil' },
            { Value2, label: 'coconut water' },
            { Value2, label: 'cod' },
            { Value2, label: 'coffee' },
            { Value2, label: 'cognac' },
            { Value2, label: 'cola' },
            { Value2, label: 'colby jack' },
            { Value2, label: 'collard greens' },
            { Value2, label: 'condensed cream of celery soup' },
            { Value2, label: 'condensed cream of mushroom soup' },
            {
                Value2, label: 'confectioner swerve'
            },
            { Value2, label: 'cooked bacon' },
            { Value2, label: 'cooked brown rice' },
            { Value2, label: 'cooked chicken breast' },
            { Value2, label: 'cooked ham' },
            { Value2, label: 'cooked long grain rice' },
            { Value2, label: 'cooked pasta' },
            { Value2, label: 'cooked polenta' },
            { Value2, label: 'cooked quinoa' },
            { Value2, label: 'cooked wild rice' },
            { Value2, label: 'cookies' },
            { Value2, label: 'coriander' },
            { Value2, label: 'corn' },
            { Value2, label: 'corn bread mix' },
            { Value2, label: 'corn chips' },
            { Value2, label: 'corn flakes cereal' },
            { Value2, label: 'corn flour' },
            { Value2, label: 'corn kernels' },
            { Value2, label: 'corn oil' },
            { Value2, label: 'corn tortillas' },
            { Value2, label: 'cornbread' },
            { Value2, label: 'corned beef' },
            { Value2, label: 'cornish hens' },
            { Value2, label: 'cornmeal' },
            { Value2, label: 'cornstarch' },
            { Value2, label: 'cotija cheese' },
            { Value2, label: 'cottage cheese' },
            { Value2, label: 'country bread' },
            { Value2, label: 'courgettes' },
            { Value2, label: 'couscous' },
            { Value2, label: 'cow pea' },
            { Value2, label: 'crabmeat' },
            { Value2, label: 'cracked pepper' },
            { Value2, label: 'cranberries' },
            { Value2, label: 'cranberry juice' },
            { Value2, label: 'cream' },
            { Value2, label: 'cream cheese' },
            { Value2, label: 'cream cheese block' },
            { Value2, label: 'cream of chicken soup' },
            { Value2, label: 'cream of tartar' },
            { Value2, label: 'creamed corn' },
            { Value2, label: 'creamy peanut butter' },
            { Value2, label: 'creme fraiche' },
            { Value2, label: 'cremini mushrooms' },
            { Value2, label: 'creole seasoning' },
            { Value2, label: 'crisp rice cereal' },
            { Value2, label: 'croutons' },
            { Value2, label: 'crystallized ginger' },
            { Value2, label: 'cucumber' },
            { Value2, label: 'cumin seeds' },
            { Value2, label: 'cup cake' },
            { Value2, label: 'currants' },
            { Value2, label: 'curry leaves' },
            { Value2, label: 'dairy free milk' },
            { Value2, label: 'dark brown sugar' },
            { Value2, label: 'dark chocolate' },
            { Value2, label: 'dark chocolate candy bars' },
            { Value2, label: 'dark chocolate chips' },
            { Value2, label: 'dark sesame oil' },
            { Value2, label: 'dates' },
            { Value2, label: 'deep dish pie crust' },
            { Value2, label: 'deli ham' },
            { Value2, label: 'deli turkey' },
            { Value2, label: 'dessert oats' },
            { Value2, label: 'dessert wine' },
            { Value2, label: 'diced ham' },
            { Value2, label: 'diet pop' },
            { Value2, label: 'dijon mustard' },
            { Value2, label: 'dill' },
            { Value2, label: 'dill pickles' },
            { Value2, label: 'hot dog' },
            { Value2, label: 'double cream' },
            { Value2, label: 'dried apricots' },
            { Value2, label: 'dried basil' },
            { Value2, label: 'dried cherries' },
            { Value2, label: 'dried chorizo' },
            { Value2, label: 'dried cranberries' },
            { Value2, label: 'dried dill' },
            { Value2, label: 'dried onion' },
            { Value2, label: 'dried porcini mushrooms' },
            { Value2, label: 'dried rubbed sage' },
            { Value2, label: 'dried thyme' },
            { Value2, label: 'dried tomatoes' },
            { Value2, label: 'dry bread crumbs' },
            { Value2, label: 'dry milk' },
            { Value2, label: 'dry mustard' },
            { Value2, label: 'dry red wine' },
            { Value2, label: 'dry roasted peanuts' },
            { Value2, label: 'duck fat' },
            { Value2, label: 'dutch process cocoa powder' },
            { Value2, label: 'edamame' },
            { Value2, label: 'egg substitute' },
            { Value2, label: 'egg vermicelli' },
            { Value2, label: 'egg whites' },
            { Value2, label: 'egg yolk' },
            { Value2, label: 'eggnog' },
            { Value2, label: 'eggplant' },
            { Value2, label: 'elbow macaroni' },
            { Value2, label: 'enchilada sauce' },
            { Value2, label: 'english cucumber' },
            { Value2, label: 'english muffin' },
            { Value2, label: 'erythritol' },
            { Value2, label: 'escarole' },
            { Value2, label: 'espresso' },
            { Value2, label: 'evaporated milk' },
            { Value2, label: 'extra firm tofu' },
            { Value2, label: 'extra virgin olive oil' },
            { Value2, label: 'farfalle' },
            { Value2, label: 'farro' },
            { Value2, label: 'fat free mayo' },
            { Value2, label: 'fat-free less-sodium chicken broth' },
            { Value2, label: 'fennel' },
            { Value2, label: 'fennel seeds' },
            { Value2, label: 'fenugreek leaf' },
            { Value2, label: 'fenugreek seeds' },
            { Value2, label: 'feta cheese' },
            { Value2, label: 'fettuccine' },
            { Value2, label: 'fire roasted tomatoes' },
            { Value2, label: 'fish' },
            { Value2, label: 'fish sauce' },
            { Value2, label: 'fish stock' },
            { Value2, label: 'flank steak' },
            { Value2, label: 'flax seeds' },
            { Value2, label: 'fleur de sel' },
            { Value2, label: 'flour' },
            { Value2, label: 'flour tortillas' },
            { Value2, label: 'fontina cheese' },
            { Value2, label: 'food dye' },
            {
                Value2, label: 'frank redhot sauce'
            },
            { Value2, label: 'free range eggs' },
            { Value2, label: 'french bread' },
            { Value2, label: 'fresh basil' },
            { Value2, label: 'fresh bean sprouts' },
            { Value2, label: 'fresh chives' },
            { Value2, label: 'fresh corn' },
            { Value2, label: 'fresh corn kernels' },
            { Value2, label: 'fresh figs' },
            { Value2, label: 'fresh fruit' },
            { Value2, label: 'fresh herbs' },
            { Value2, label: 'fresh mint' },
            { Value2, label: 'fresh mozzarella' },
            { Value2, label: 'fresh rosemary' },
            { Value2, label: 'fresh thyme leaves' },
            { Value2, label: 'fried onions' },
            { Value2, label: 'frosting' },
            { Value2, label: 'froyo bars' },
            { Value2, label: 'frozen corn' },
            { Value2, label: 'frozen spinach' },
            { Value2, label: 'fudge' },
            { Value2, label: 'fudge topping' },
            { Value2, label: 'fun size almond joy bar' },
            { Value2, label: 'garam masala' },
            { Value2, label: 'garbanzo bean flour' },
            { Value2, label: 'garlic' },
            { Value2, label: 'garlic paste' },
            { Value2, label: 'garlic powder' },
            { Value2, label: 'garlic powder' },
            { Value2, label: 'garlic salt' },
            { Value2, label: 'gelatin' },
            { Value2, label: 'gf chocolate cake mix' },
            { Value2, label: 'gin' },
            { Value2, label: 'ginger' },
            { Value2, label: 'ginger ale' },
            { Value2, label: 'ginger paste' },
            { Value2, label: 'ginger-garlic paste' },
            { Value2, label: 'gingersnap cookies' },
            { Value2, label: 'gnocchi' },
            { Value2, label: 'goat cheese' },
            { Value2, label: 'golden raisins' },
            { Value2, label: 'gorgonzola' },
            { Value2, label: 'gouda cheese' },
            { Value2, label: 'graham cracker crumbs' },
            { Value2, label: 'graham cracker pie crust' },
            { Value2, label: 'graham crackers' },
            { Value2, label: 'grain blend' },
            { Value2, label: 'grand marnier' },
            { Value2, label: 'granny smith apples' },
            { Value2, label: 'granola' },
            { Value2, label: 'granulated garlic' },
            { Value2, label: 'grape tomatoes' },
            { Value2, label: 'grapefruit' },
            { Value2, label: 'grapeseed oil' },
            { Value2, label: 'gravy' },
            { Value2, label: 'great northern beans' },
            { Value2, label: 'greek yogurt' },
            { Value2, label: 'green beans' },
            { Value2, label: 'green bell pepper' },
            { Value2, label: 'green chili pepper' },
            { Value2, label: 'green food coloring' },
            { Value2, label: 'green grapes' },
            { Value2, label: 'green olives' },
            { Value2, label: 'green onions' },
            { Value2, label: 'greens' },
            { Value2, label: 'grill cheese' },
            { Value2, label: 'grill seasoning' },
            { Value2, label: 'ground allspice' },
            { Value2, label: 'ground ancho chili' },
            { Value2, label: 'ground beef' },
            { Value2, label: 'ground chicken' },
            { Value2, label: 'ground chipotle chile pepper' },
            { Value2, label: 'ground cinnamon' },
            { Value2, label: 'ground cinnamon' },
            { Value2, label: 'ground cloves' },
            { Value2, label: 'ground coriander seeds' },
            { Value2, label: 'ground cumin' },
            { Value2, label: 'ground flaxseed' },
            { Value2, label: 'ground ginger' },
            { Value2, label: 'ground lamb' },
            { Value2, label: 'ground mace' },
            { Value2, label: 'ground nutmeg' },
            { Value2, label: 'ground pork' },
            { Value2, label: 'ground pork sausage' },
            { Value2, label: 'ground veal' },
            { Value2, label: 'gruyere' },
            { Value2, label: 'guacamole' },
            { Value2, label: 'half n half' },
            { Value2, label: 'halibut fillet' },
            { Value2, label: 'ham' },
            { Value2, label: 'hamburger buns' },
            { Value2, label: 'hard cooked eggs' },
            { Value2, label: 'harissa' },
            { Value2, label: 'hash brown potatoes' },
            { Value2, label: 'hazelnuts' },
            { Value2, label: 'healthy request cream of celery soup' },
            { Value2, label: 'hemp seeds' },
            { Value2, label: 'herbes de provence' },
            { Value2, label: 'herbs' },
            {
                Value2, label: 'hershey kisses brand milk chocolates'
            },
            { Value2, label: 'hoisin sauce' },
            { Value2, label: 'honey mustard' },
            { Value2, label: 'horseradish' },
            { Value2, label: 'hot sauce' },
            { Value2, label: 'hummus' },
            { Value2, label: 'ice' },
            { Value2, label: 'ice cream' },
            { Value2, label: 'instant chocolate pudding mix' },
            { Value2, label: 'instant coffee powder' },
            { Value2, label: 'instant espresso powder' },
            { Value2, label: 'instant lemon pudding mix' },
            { Value2, label: 'instant yeast' },
            { Value2, label: 'irish cream' },
            { Value2, label: 'italian bread' },
            { Value2, label: 'italian cheese blend' },
            { Value2, label: 'italian sausages' },
            { Value2, label: 'italian seasoning' },
            { Value2, label: 'jaggery' },
            { Value2, label: 'jalapeno' },
            { Value2, label: 'jasmine rice' },
            { Value2, label: 'jelly' },
            { Value2, label: 'jicama' },
            { Value2, label: 'jimmies' },
            { Value2, label: 'juice' },
            { Value2, label: 'jumbo shell pasta' },
            { Value2, label: 'kaffir lime leaves' },
            { Value2, label: 'kahlua' },
            { Value2, label: 'kalamata olives' },
            { Value2, label: 'kale' },
            { Value2, label: 'ketchup' },
            { Value2, label: 'kitchen bouquet' },
            { Value2, label: 'kiwis' },
            { Value2, label: 'kosher salt' },
            { Value2, label: 'ladyfingers' },
            { Value2, label: 'lamb' },
            { Value2, label: 'lasagna noodles' },
            { Value2, label: 'lb cake' },
            { Value2, label: 'lean ground beef' },
            { Value2, label: 'lean ground turkey' },
            { Value2, label: 'lean pork tenderloin' },
            { Value2, label: 'leeks' },
            { Value2, label: 'leg of lamb' },
            { Value2, label: 'lemon' },
            { Value2, label: 'lemon curd' },
            { Value2, label: 'lemon extract' },
            { Value2, label: 'lemon juice' },
            { Value2, label: 'lemon peel' },
            { Value2, label: 'lemon pepper' },
            { Value2, label: 'lemon wedges' },
            { Value2, label: 'lemongrass' },
            { Value2, label: 'lettuce' },
            { Value2, label: 'lettuce leaves' },
            { Value2, label: 'light butter' },
            { Value2, label: 'light coconut milk' },
            { Value2, label: 'light corn syrup' },
            { Value2, label: 'light cream cheese' },
            { Value2, label: 'light mayonnaise' },
            { Value2, label: 'light olive oil' },
            { Value2, label: 'light soy sauce' },
            { Value2, label: 'lime' },
            { Value2, label: 'lime juice' },
            { Value2, label: 'lime wedges' },
            { Value2, label: 'lime zest' },
            { Value2, label: 'linguine' },
            { Value2, label: 'liquid smoke' },
            { Value2, label: 'liquid stevia' },
            { Value2, label: 'liquor' },
            { Value2, label: 'live lobster' },
            { Value2, label: 'long-grain rice' },
            { Value2, label: 'low fat buttermilk' },
            { Value2, label: 'low fat milk' },
            { Value2, label: 'low fat milk' },
            { Value2, label: 'low fat plain yogurt' },
            { Value2, label: 'low fat ricotta cheese' },
            { Value2, label: 'low fat sour cream' },
            { Value2, label: 'low sodium chicken broth' },
            { Value2, label: 'low sodium soy sauce' },
            { Value2, label: 'low-sodium chicken stock' },
            { Value2, label: 'lower sodium beef broth' },
            { Value2, label: 'lump crab' },
            { Value2, label: 'm&m candies' },
            { Value2, label: 'macadamia nuts' },
            { Value2, label: 'macaroni and cheese mix' },
            { Value2, label: 'madras curry powder' },
            { Value2, label: 'malt drink mix' },
            { Value2, label: 'mandarin orange sections' },
            { Value2, label: 'mandarin oranges' },
            { Value2, label: 'mango' },
            { Value2, label: 'maple syrup' },
            { Value2, label: 'maraschino cherries' },
            { Value2, label: 'margarine' },
            { Value2, label: 'marinara sauce' },
            { Value2, label: 'marjoram' },
            { Value2, label: 'marsala wine' },
            { Value2, label: 'marshmallow fluff' },
            { Value2, label: 'marshmallows' },
            { Value2, label: 'masa harina' },
            { Value2, label: 'mascarpone' },
            { Value2, label: 'mat beans' },
            { Value2, label: 'matcha tea' },
            { Value2, label: 'mayonnaise' },
            { Value2, label: 'meat' },
            { Value2, label: 'meat' },
            { Value2, label: 'meatballs' },
            { Value2, label: 'medjool dates' },
            { Value2, label: 'mexican cream' },
            { Value2, label: 'meyer lemon juice' },
            { Value2, label: 'milk' },
            { Value2, label: 'milk chocolate chips' },
            { Value2, label: 'mint chutney' },
            { Value2, label: 'minute rice' },
            { Value2, label: 'miracle whip' },
            { Value2, label: 'mirin' },
            { Value2, label: 'miso' },
            { Value2, label: 'molasses' },
            { Value2, label: 'monterey jack cheese' },
            { Value2, label: 'mushroom' },
            { Value2, label: 'mussels' },
            { Value2, label: 'mustard' },
            { Value2, label: 'mustard seeds' },
            { Value2, label: 'napa cabbage' },
            { Value2, label: 'navel oranges' },
            { Value2, label: 'nectarine' },
            { Value2, label: 'new potatoes' },
            { Value2, label: 'non-fat greek yogurt' },
            { Value2, label: 'nonfat cool whip' },
            { Value2, label: 'nonfat milk' },
            { Value2, label: 'nori' },
            { Value2, label: 'nut butter' },
            { Value2, label: 'nut meal' },
            { Value2, label: 'nutella' },
            { Value2, label: 'nutritional yeast' },
            { Value2, label: 'oat flour' },
            { Value2, label: 'oats' },
            { Value2, label: 'oil' },
            { Value2, label: 'oil packed sun dried tomatoes' },
            { Value2, label: 'okra' },
            { Value2, label: 'old bay seasoning' },
            { Value2, label: 'olive oil' },
            { Value2, label: 'olives' },
            { Value2, label: 'onion' },
            { Value2, label: 'onion powder' },
            { Value2, label: 'onion soup mix' },
            { Value2, label: 'orange' },
            { Value2, label: 'orange bell pepper' },
            { Value2, label: 'orange juice' },
            { Value2, label: 'orange juice concentrate' },
            { Value2, label: 'orange liqueur' },
            { Value2, label: 'orange marmalade' },
            { Value2, label: 'orange oil' },
            { Value2, label: 'orange zest' },
            { Value2, label: 'oregano' },
            { Value2, label: 'oreo cookies' },
            { Value2, label: 'orzo' },
            { Value2, label: 'oyster sauce' },
            { Value2, label: 'oysters' },
            { Value2, label: 'palm sugar' },
            { Value2, label: 'pancetta' },
            { Value2, label: 'paneer' },
            { Value2, label: 'panko' },
            { Value2, label: 'papaya' },
            { Value2, label: 'paprika' },
            { Value2, label: 'parmigiano reggiano' },
            { Value2, label: 'parsley' },
            { Value2, label: 'parsley flakes' },
            { Value2, label: 'parsnip' },
            { Value2, label: 'part-skim mozzarella cheese' },
            { Value2, label: 'pasta' },
            { Value2, label: 'pasta salad mix' },
            { Value2, label: 'pasta sauce' },
            { Value2, label: 'pastry flour' },
            { Value2, label: 'peach' },
            { Value2, label: 'peanut butter' },
            { Value2, label: 'peanut butter chips' },
            { Value2, label: 'peanut butter cups' },
            { Value2, label: 'peanut oil' },
            { Value2, label: 'peanuts' },
            { Value2, label: 'pear liqueur' },
            { Value2, label: 'pearl barley' },
            { Value2, label: 'pearl onions' },
            { Value2, label: 'peas' },
            { Value2, label: 'pecan' },
            { Value2, label: 'pecan pieces' },
            { Value2, label: 'pecorino' },
            { Value2, label: 'penne' },
            { Value2, label: 'peperoncino' },
            { Value2, label: 'pepper jack cheese' },
            { Value2, label: 'peppercorns' },
            { Value2, label: 'peppermint baking chips' },
            { Value2, label: 'peppermint extract' },
            { Value2, label: 'pepperoni' },
            { Value2, label: 'peppers' },
            { Value2, label: 'pesto' },
            { Value2, label: 'pickle relish' },
            { Value2, label: 'pickles' },
            { Value2, label: 'pico de gallo' },
            { Value2, label: 'pie crust' },
            { Value2, label: 'pimento stuffed olives' },
            { Value2, label: 'pimientos' },
            { Value2, label: 'pine nuts' },
            { Value2, label: 'pineapple' },
            { Value2, label: 'pineapple chunks' },
            { Value2, label: 'pineapple in juice' },
            { Value2, label: 'pineapple juice' },
            { Value2, label: 'pink himalayan salt' },
            { Value2, label: 'pinto beans' },
            { Value2, label: 'pistachios' },
            { Value2, label: 'pita' },
            { Value2, label: 'pizza crust' },
            { Value2, label: 'pizza mix' },
            { Value2, label: 'plain greek yogurt' },
            { Value2, label: 'plain nonfat yogurt' },
            { Value2, label: 'plain yogurt' },
            { Value2, label: 'plantain' },
            { Value2, label: 'plum' },
            { Value2, label: 'plum tomatoes' },
            { Value2, label: 'poblano peppers' },
            { Value2, label: 'polenta' },
            { Value2, label: 'polish sausage' },
            { Value2, label: 'pomegranate juice' },
            { Value2, label: 'pomegranate molasses' },
            { Value2, label: 'pomegranate seeds' },
            { Value2, label: 'popcorn' },
            { Value2, label: 'poppy seeds' },
            { Value2, label: 'pork' },
            { Value2, label: 'Pork & Beans' },
            { Value2, label: 'pork belly' },
            { Value2, label: 'pork butt' },
            { Value2, label: 'pork chops' },
            { Value2, label: 'pork links' },
            { Value2, label: 'pork loin chops' },
            { Value2, label: 'pork loin roast' },
            { Value2, label: 'pork roast' },
            { Value2, label: 'pork shoulder' },
            { Value2, label: 'pork tenderloin' },
            { Value2, label: 'port' },
            { Value2, label: 'portabella mushrooms' },
            { Value2, label: 'pot roast' },
            { Value2, label: 'potato chips' },
            { Value2, label: 'potato starch' },
            { Value2, label: 'potatoes' },
            { Value2, label: 'poultry seasoning' },
            { Value2, label: 'powdered sugar' },
            { Value2, label: 'pretzel sandwiches' },
            { Value2, label: 'processed american cheese' },
            { Value2, label: 'prosciutto' },
            { Value2, label: 'provolone cheese' },
            { Value2, label: 'prunes' },
            { Value2, label: 'puff pastry' },
            { Value2, label: 'pumpkin' },
            { Value2, label: 'pumpkin pie filling' },
            { Value2, label: 'pumpkin pie spice' },
            { Value2, label: 'pumpkin puree' },
            { Value2, label: 'pumpkin seeds' },
            { Value2, label: 'queso fresco' },
            { Value2, label: 'quick cooking oats' },
            { Value2, label: 'quinoa' },
            { Value2, label: 'quinoa flour' },
            { Value2, label: 'radicchio' },
            { Value2, label: 'radishes' },
            { Value2, label: 'raisins' },
            { Value2, label: 'rajma masala' },
            { Value2, label: 'ramen noodles' },
            { Value2, label: 'ranch dressing' },
            { Value2, label: 'ranch dressing mix' },
            { Value2, label: 'raspberries' },
            { Value2, label: 'raspberry jam' },
            { Value2, label: 'raw cashews' },
            { Value2, label: 'raw shrimp' },
            { Value2, label: 'ready-to-serve Asian fried rice' },
            { Value2, label: 'real bacon recipe pieces' },
            { Value2, label: 'red apples' },
            { Value2, label: 'red bell peppers' },
            { Value2, label: 'red cabbage' },
            { Value2, label: 'red chilli' },
            { Value2, label: 'red delicious apples' },
            { Value2, label: 'red food coloring' },
            { Value2, label: 'red grapefruit juice' },
            { Value2, label: 'red grapes' },
            { Value2, label: 'red kidney beans' },
            { Value2, label: 'red lentils' },
            { Value2, label: 'red onion' },
            { Value2, label: 'red pepper flakes' },
            { Value2, label: 'red pepper powder' },
            { Value2, label: 'red potatoes' },
            { Value2, label: 'red velvet cookie' },
            { Value2, label: 'red wine' },
            { Value2, label: 'red wine vinegar' },
            { Value2, label: 'reduced fat shredded cheddar cheese' },
            { Value2, label: 'refried beans' },
            { Value2, label: 'refrigerated crescent rolls' },
            { Value2, label: 'refrigerated pizza dough' },
            { Value2, label: 'refrigerated sugar cookie dough' },
            { Value2, label: 'rhubarb' },
            { Value2, label: 'rib tips' },
            { Value2, label: 'rice' },
            { Value2, label: 'rice flour' },
            { Value2, label: 'rice krispies cereal' },
            { Value2, label: 'rice milk' },
            { Value2, label: 'rice noodles' },
            { Value2, label: 'rice paper' },
            { Value2, label: 'rice syrup' },
            { Value2, label: 'rice vinegar' },
            { Value2, label: 'rice wine' },
            { Value2, label: 'ricotta salata' },
            { Value2, label: 'ritz crackers' },
            { Value2, label: 'roast beef' },
            { Value2, label: 'roasted chicken' },
            { Value2, label: 'roasted nuts' },
            { Value2, label: 'roasted peanuts' },
            { Value2, label: 'roasted red peppers' },
            { Value2, label: 'roma tomatoes' },
            { Value2, label: 'romaine lettuce' },
            { Value2, label: 'root vegetables' },
            { Value2, label: 'rosemary' },
            { Value2, label: 'rotini pasta' },
            { Value2, label: 'rotisserie chicken' },
            { Value2, label: 'round steak' },
            { Value2, label: 'rub' },
            { Value2, label: 'rum extract' },
            { Value2, label: 'runny honey' },
            { Value2, label: 'russet potatoes' },
            { Value2, label: 'rutabaga' },
            { Value2, label: 'rye bread' },
            { Value2, label: 'rye meal' },
            { Value2, label: 'saffron threads' },
            { Value2, label: 'sage' },
            { Value2, label: 'sage leaves' },
            { Value2, label: 'salad dressing' },
            { Value2, label: 'salami' },
            { Value2, label: 'salmon fillet' },
            { Value2, label: 'salsa' },
            { Value2, label: 'salsa verde' },
            { Value2, label: 'salt' },
            { Value2, label: 'salt and pepper' },
            { Value2, label: 'salted butter' },
            { Value2, label: 'saltine crackers' },
            { Value2, label: 'sandwich bun' },
            { Value2, label: 'sauerkraut' },
            { Value2, label: 'sausage' },
            { Value2, label: 'sausage links' },
            { Value2, label: 'scotch bonnet chili' },
            { Value2, label: 'sea salt' },
            { Value2, label: 'sea scallops' },
            { Value2, label: 'seasoned bread crumbs' },
            { Value2, label: 'seasoned rice vinegar' },
            { Value2, label: 'seasoned salt' },
            { Value2, label: 'seasoning' },
            { Value2, label: 'seasoning blend' },
            { Value2, label: 'seeds' },
            { Value2, label: 'self-rising flour' },
            { Value2, label: 'semi sweet chocolate chips' },
            { Value2, label: 'serrano chile' },
            { Value2, label: 'sesame oil' },
            { Value2, label: 'sesame seed hamburger buns' },
            { Value2, label: 'sesame seeds' },
            { Value2, label: 'shallot' },
            { Value2, label: 'sharp cheddar cheese' },
            { Value2, label: 'sheeps milk cheese' },
            { Value2, label: 'shells' },
            { Value2, label: 'sherry' },
            { Value2, label: 'sherry' },
            { Value2, label: 'sherry vinegar' },
            { Value2, label: 'shiitake mushroom caps' },
            { Value2, label: 'short grain rice' },
            { Value2, label: 'short pasta' },
            { Value2, label: 'short ribs' },
            { Value2, label: 'shortbread cookies' },
            { Value2, label: 'shortcrust pastry' },
            { Value2, label: 'shortening' },
            { Value2, label: 'shredded cheddar cheese' },
            { Value2, label: 'shredded cheese' },
            { Value2, label: 'shredded chicken' },
            { Value2, label: 'shredded coconut' },
            { Value2, label: 'shredded mexican cheese blend' },
            { Value2, label: 'shredded mexican cheese blend' },
            { Value2, label: 'shredded mozzarella' },
            { Value2, label: 'silken tofu' },
            { Value2, label: 'sirloin steak' },
            { Value2, label: 'skim milk ricotta' },
            { Value2, label: 'skim vanilla greek yogurt' },
            { Value2, label: 'skin-on bone-in chicken leg quarters' },
            { Value2, label: 'skinless boneless chicken breast halves' },
            { Value2, label: 'skinless boneless chicken thighs' },
            { Value2, label: 'skinned black gram' },
            { Value2, label: 'slaw dressing' },
            { Value2, label: 'slaw mix' },
            { Value2, label: 'slivered almonds' },
            { Value2, label: 'smoked paprika' },
            { Value2, label: 'smoked salmon' },
            { Value2, label: 'smoked sausage' },
            { Value2, label: 'smooth peanut butter' },
            { Value2, label: 'snapper fillets' },
            { Value2, label: 'snow peas' },
            { Value2, label: 'soda water' },
            { Value2, label: 'sour cream' },
            { Value2, label: 'sourdough bowl' },
            { Value2, label: 'sourdough bread' },
            { Value2, label: 'soy milk' },
            { Value2, label: 'soy protein powder' },
            { Value2, label: 'soy sauce' },
            { Value2, label: 'spaghetti' },
            { Value2, label: 'spaghetti squash' },
            { Value2, label: 'sparkling wine' },
            { Value2, label: 'spelt flour' },
            { Value2, label: 'spicy brown mustard' },
            { Value2, label: 'spinach' },
            { Value2, label: 'sprite' },
            { Value2, label: 'sprouts' },
            { Value2, label: 'squash' },
            { Value2, label: 'sriracha sauce' },
            { Value2, label: 'steaks' },
            { Value2, label: 'steel cut oats' },
            { Value2, label: 'stevia' },
            { Value2, label: 'stew meat' },
            { Value2, label: 'stew vegetables' },
            { Value2, label: 'stock' },
            { Value2, label: 'store-bought phyllo' },
            { Value2, label: 'stout' },
            { Value2, label: 'strawberries' },
            { Value2, label: 'strawberry jam' },
            { Value2, label: 'strawberry jello' },
            { Value2, label: 'stuffing' },
            { Value2, label: 'stuffing mix' },
            { Value2, label: 'sub rolls' },
            { Value2, label: 'sugar' },
            { Value2, label: 'sugar snap peas' },
            { Value2, label: 'sugar syrup' },
            { Value2, label: 'sukrin sweetener' },
            { Value2, label: 'summer savory' },
            { Value2, label: 'summer squash' },
            { Value2, label: 'sunflower oil' },
            { Value2, label: 'sunflower seeds' },
            { Value2, label: 'sweet chilli sauce' },
            { Value2, label: 'sweet onion' },
            { Value2, label: 'sweet paprika' },
            { Value2, label: 'sweet pickle juice' },
            { Value2, label: 'sweet pickle relish' },
            { Value2, label: 'sweet potato' },
            { Value2, label: 'sweet tea' },
            { Value2, label: 'sweetened coconut' },
            { Value2, label: 'sweetened condensed milk' },
            { Value2, label: 'sweetened shredded coconut' },
            { Value2, label: 'swiss chard' },
            { Value2, label: 'swiss cheese' },
            { Value2, label: 'taco seasoning mix' },
            { Value2, label: 'taco shells' },
            { Value2, label: 'tahini' },
            { Value2, label: 'tamari' },
            { Value2, label: 'tapioca flour' },
            { Value2, label: 'tarragon' },
            { Value2, label: 'tart apple' },
            { Value2, label: 'tea bags' },
            { Value2, label: 'tequila' },
            { Value2, label: 'teriyaki sauce' },
            { Value2, label: 'thai basil' },
            { Value2, label: 'thai chiles' },
            { Value2, label: 'thai red curry paste' },
            { Value2, label: 'thick-cut bacon' },
            { Value2, label: 'tilapia fillets' },
            { Value2, label: 'toast' },
            { Value2, label: 'toffee bits' },
            { Value2, label: 'tofu' },
            { Value2, label: 'tomatillos' },
            { Value2, label: 'tomato juice' },
            { Value2, label: 'tomato paste' },
            { Value2, label: 'tomato puree' },
            { Value2, label: 'tomato sauce' },
            { Value2, label: 'tomato soup' },
            { Value2, label: 'tomatoes' },
            { Value2, label: 'top blade steak' },
            { Value2, label: 'top round steak' },
            { Value2, label: 'Top Sirloin' },
            { Value2, label: 'tortilla' },
            { Value2, label: 'tortilla chips' },
            { Value2, label: 'triple sec' },
            { Value2, label: 'truffle oil' },
            { Value2, label: 'tuna' },
            { Value2, label: 'turbinado sugar' },
            { Value2, label: 'turkey' },
            { Value2, label: 'turkey breast' },
            { Value2, label: 'turkey kielbasa' },
            { Value2, label: 'turmeric' },
            { Value2, label: 'turnips' },
            { Value2, label: 'unbleached flour' },
            { Value2, label: 'unsalted butter' },
            { Value2, label: 'unsmoked back bacon' },
            { Value2, label: 'unsweetened applesauce' },
            { Value2, label: 'unsweetened coconut milk' },
            { Value2, label: 'unsweetened shredded coconut' },
            { Value2, label: 'vanilla bean' },
            { Value2, label: 'vanilla bean paste' },
            { Value2, label: 'vanilla essence' },
            { Value2, label: 'vanilla extract' },
            { Value2, label: 'vanilla frosting' },
            { Value2, label: 'vanilla instant pudding mix' },
            { Value2, label: 'vanilla protein powder' },
            { Value2, label: 'vanilla wafers' },
            { Value2, label: 'vanilla yogurt' },
            { Value2, label: 'vegan cheese' },
            { Value2, label: 'vegan chocolate chips' },
            { Value2, label: 'vegan margarine' },
            { Value2, label: 'vegetable broth' },
            { Value2, label: 'vegetable oil' },
            { Value2, label: 'vegetarian bacon' },
            { Value2, label: 'vermouth' },
            { Value2, label: 'vinaigrette' },
            { Value2, label: 'vinegar' },
            { Value2, label: 'vodka' },
            { Value2, label: 'walnuts' },
            { Value2, label: 'water' },
            { Value2, label: 'water chestnuts' },
            { Value2, label: 'water-packed tuna' },
            { Value2, label: 'watercress' },
            { Value2, label: 'watermelon chunks' },
            { Value2, label: 'wheat bran' },
            { Value2, label: 'wheat germ' },
            { Value2, label: 'whipped cream' },
            { Value2, label: 'whipped topping' },
            { Value2, label: 'whipping cream' },
            { Value2, label: 'whiskey' },
            { Value2, label: 'white balsamic vinegar' },
            { Value2, label: 'white bread' },
            { Value2, label: 'white cake mix' },
            { Value2, label: 'white cheddar' },
            { Value2, label: 'white chocolate' },
            { Value2, label: 'white chocolate chips' },
            { Value2, label: 'white onion' },
            { Value2, label: 'white pepper' },
            { Value2, label: 'white whole wheat flour' },
            { Value2, label: 'white wine' },
            { Value2, label: 'white wine vinegar' },
            { Value2, label: 'whole allspice berries' },
            { Value2, label: 'whole chicken' },
            { Value2, label: 'whole coriander seeds' },
            { Value2, label: 'whole cranberry sauce' },
            { Value2, label: 'whole kernel corn' },
            { Value2, label: 'whole star anise' },
            { Value2, label: 'whole wheat bread' },
            { Value2, label: 'whole wheat flour' },
            { Value2, label: 'whole wheat tortillas' },
            { Value2, label: 'whole-grain mustard' },
            { Value2, label: 'wine' },
            { Value2, label: 'wine vinegar' },
            { Value2, label: 'winter squash' },
            { Value2, label: 'won ton wraps' },
            { Value2, label: 'worcestershire sauce' },
            { Value2, label: 'wraps' },
            { Value2, label: 'xanthan gum' },
            { Value2, label: 'yeast' },
            { Value2, label: 'yellow bell pepper' },
            { Value2, label: 'yellow cake mix' },
            { Value2, label: 'yellow onion' },
            { Value2, label: 'yogurt' },
            { Value2, label: 'yukon gold potato' }

        ]);
    };

    const add_ingredient_to_lst = () => {
        let lst = document.getElementById("list");
        // let selected_set = lst.innerHTML.split('<br>');

        let flag = 1;
        if (Value2.label == undefined) flag = 0;

        if (flag) {
            let li = document.createElement('li');
            li.innerHTML = Value2.label;
            li.classList.add("item");
            lst.appendChild(li);

            let span = document.createElement("span");
            span.innerHTML = "\u00d7";
            span.classList.add("span");
            span.addEventListener("click", function (e) {
                if (e.target.tagName === "SPAN") {
                    e.target.parentElement.remove();
                }
            }, false);
            li.appendChild(span);
        }
    }

    // document.getElementById("list").addEventListener("click", function(e){
    //   if(e.target.tagName === "SPAN"){
    //     e.tagName.parentElement.remove();
    //   }
    // },false);  

    const get_recipe_from_api = async () => {
        let queryy = "";
        let lst = document.getElementById("list");
        let selected_set = lst.innerHTML.split('<br>');

        let flag = 1;
        if (selected_set.length == 1 && selected_set[0] == '') flag = 0;

        selected_set.forEach(ingredient => {
            if (ingredient != '')
                queryy += ingredient + ",+";
        })

        queryy = queryy.slice(0, -2);

        if (flag) {
            let recipies = document.getElementById("recipes")

            const options2 = { method: 'GET' };

            const options = { method: 'GET' };

            const raw_response = await fetch(`https://api.spoonacular.com/food/videos/search?number=10&apiKey=7f7543ed5a09491c8d1e89145f5caf81&includeIngredients=${queryy}`, options2)

            console.log(queryy);

            // const raw_response = await fetch(`https://api.spoonacular.com/recipes/search?apiKey=7f7543ed5a09491c8d1e89145f5caf81&includeIngredients=${queryy}&instructionsRequired=true&addRecipeInstructions=true`,options2)

            const response = await raw_response.json();

            localStorage.setItem('last-video-search', JSON.stringify(response))
            setdum2(dum2 + 1)

        }

        else alert(`Please select at least one ingredient`);
    }


    const clear = () => {
        // localStorage.setItem('last-video-search', JSON.stringify([]));
        localStorage.removeItem('last-video-search');
        window.location.reload();
    }

    const customStyles = {
        option: (provided, state) => ({
            ...provided,
            backgroundColor: 'rgb(94, 92, 92)',
            color: '#fff',
        }),
    };

    return (
        <>
            <Navbar/>
            <div className="mg">
                <Select id="ing" className="searchBar"
                    Value={Value2}
                    onChange={handleChange}
                    onInputChange={handleInputChange}
                    options={options2}
                    styles={customStyles}
                    isClearable
                    placeholder="Type ingredients..."
                />

                <div className='button-container'>
                    <button id="add_ingredient" className='search-component-button' onClick={add_ingredient_to_lst}>Add</button>
                    <button id="get_recipe" className='search-component-button' onClick={get_recipe_from_api}>Get Yummy Recipes !!</button>
                    <button id="clear" className='search-component-button' onClick={clear}>Clear</button>
                </div>
                <ul id="list" className="lst_container"></ul>

                <div className="recipes-container">

                    {
                        [...Array(10)].map((_, index) => (
                            <Video_card key={index} ind={index} />
                        ))
                    }

                </div>
            </div>

            <Fotter />
        </>
    );

};


export default Search_video;

